<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email-address</name>
   <tag></tag>
   <elementGuidId>afa48210-f628-4b99-920b-32355344fc43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email-address&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email-address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1474c7ad-0f54-4dac-b589-2108ad98ad4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>atoms-element-input-1</value>
      <webElementGuid>33b214f7-a31e-4eb4-abb2-0a30f81017b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> o-form__element</value>
      <webElementGuid>28bc7cae-76d7-4e0c-b344-19ce9a1803dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fb0c2e98-4091-41b1-a170-aee09a7b6031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email-address</value>
      <webElementGuid>0cb808b7-882b-4502-bc6f-c791419409af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hook</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e19192d0-d897-4d44-a369-3068517b3c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[@class=&quot;o-external__main&quot;]/form[@class=&quot;o-card c-card&quot;]/div[@class=&quot;o-card__main&quot;]/div[@class=&quot;o-card__content&quot;]/section[@class=&quot;o-card__section  o-card__section--form&quot;]/label[@class=&quot;o-input o-form__object molecules-input&quot;]/input[@class=&quot;o-form__element&quot;]</value>
      <webElementGuid>95f56c03-7ea8-4fc3-9d42-e1a654285907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email-address']</value>
      <webElementGuid>74c88dc5-20f8-4f94-b3b7-6b782bf213a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/form/div/div/section[2]/label/input</value>
      <webElementGuid>348f48b0-aadd-4930-af59-94cd9c5d850c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c16a1826-4f41-495f-8a16-0f046f88a5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email-address']</value>
      <webElementGuid>6606f584-0cfd-4f54-9e75-cf53a0173626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
